/* Countdown.c generated by valac 0.34.9, the Vala compiler
 * generated from Countdown.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_BREAKER_TYPE_COUNTDOWN (type_breaker_countdown_get_type ())
#define TYPE_BREAKER_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BREAKER_TYPE_COUNTDOWN, TypeBreakerCountdown))
#define TYPE_BREAKER_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BREAKER_TYPE_COUNTDOWN, TypeBreakerCountdownClass))
#define TYPE_BREAKER_IS_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BREAKER_TYPE_COUNTDOWN))
#define TYPE_BREAKER_IS_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BREAKER_TYPE_COUNTDOWN))
#define TYPE_BREAKER_COUNTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BREAKER_TYPE_COUNTDOWN, TypeBreakerCountdownClass))

typedef struct _TypeBreakerCountdown TypeBreakerCountdown;
typedef struct _TypeBreakerCountdownClass TypeBreakerCountdownClass;
typedef struct _TypeBreakerCountdownPrivate TypeBreakerCountdownPrivate;
typedef struct _TypeBreakerParamSpecCountdown TypeBreakerParamSpecCountdown;

struct _TypeBreakerCountdown {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TypeBreakerCountdownPrivate * priv;
	guint timer;
	guint ticked;
};

struct _TypeBreakerCountdownClass {
	GTypeClass parent_class;
	void (*finalize) (TypeBreakerCountdown *self);
};

struct _TypeBreakerCountdownPrivate {
	gdouble _progress;
	guint _microseconds;
	guint seconds_left;
	guint interval;
};

struct _TypeBreakerParamSpecCountdown {
	GParamSpec parent_instance;
};


static gpointer type_breaker_countdown_parent_class = NULL;

gpointer type_breaker_countdown_ref (gpointer instance);
void type_breaker_countdown_unref (gpointer instance);
GParamSpec* type_breaker_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void type_breaker_value_set_countdown (GValue* value, gpointer v_object);
void type_breaker_value_take_countdown (GValue* value, gpointer v_object);
gpointer type_breaker_value_get_countdown (const GValue* value);
GType type_breaker_countdown_get_type (void) G_GNUC_CONST;
#define TYPE_BREAKER_COUNTDOWN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_BREAKER_TYPE_COUNTDOWN, TypeBreakerCountdownPrivate))
enum  {
	TYPE_BREAKER_COUNTDOWN_DUMMY_PROPERTY
};
TypeBreakerCountdown* type_breaker_countdown_new (guint seconds);
TypeBreakerCountdown* type_breaker_countdown_construct (GType object_type, guint seconds);
void type_breaker_countdown_set_microseconds (TypeBreakerCountdown* self, guint value);
guint type_breaker_countdown_get_microseconds (TypeBreakerCountdown* self);
void type_breaker_countdown_start (TypeBreakerCountdown* self);
gboolean type_breaker_countdown_on_interval (TypeBreakerCountdown* self);
static gboolean _type_breaker_countdown_on_interval_gsource_func (gpointer self);
void type_breaker_countdown_set_progress (TypeBreakerCountdown* self, gdouble value);
gdouble type_breaker_countdown_get_progress (TypeBreakerCountdown* self);
static void g_cclosure_user_marshal_VOID__UINT_DOUBLE (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void type_breaker_countdown_finalize (TypeBreakerCountdown* obj);


TypeBreakerCountdown* type_breaker_countdown_construct (GType object_type, guint seconds) {
	TypeBreakerCountdown* self = NULL;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	self = (TypeBreakerCountdown*) g_type_create_instance (object_type);
	_tmp0_ = seconds;
	self->priv->seconds_left = _tmp0_;
	_tmp1_ = seconds;
	type_breaker_countdown_set_microseconds (self, _tmp1_ * 1000);
	_tmp2_ = self->priv->_microseconds;
	self->timer = _tmp2_;
	_tmp3_ = self->timer;
	self->ticked = _tmp3_ / 1000;
	_tmp4_ = self->timer;
	if (_tmp4_ == ((guint) 0)) {
		g_signal_emit_by_name (self, "zero");
	}
	return self;
}


TypeBreakerCountdown* type_breaker_countdown_new (guint seconds) {
	return type_breaker_countdown_construct (TYPE_BREAKER_TYPE_COUNTDOWN, seconds);
}


static gboolean _type_breaker_countdown_on_interval_gsource_func (gpointer self) {
	gboolean result;
	result = type_breaker_countdown_on_interval ((TypeBreakerCountdown*) self);
	return result;
}


void type_breaker_countdown_start (TypeBreakerCountdown* self) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->interval;
	g_timeout_add_full (G_PRIORITY_DEFAULT_IDLE, _tmp0_, _type_breaker_countdown_on_interval_gsource_func, type_breaker_countdown_ref (self), type_breaker_countdown_unref);
}


gboolean type_breaker_countdown_on_interval (TypeBreakerCountdown* self) {
	gboolean result = FALSE;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	guint _tmp5_ = 0U;
	gdouble _tmp6_ = 0.0;
	guint _tmp7_ = 0U;
	guint _tmp8_ = 0U;
	guint _tmp12_ = 0U;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->timer;
	_tmp1_ = self->priv->interval;
	self->timer = _tmp0_ - _tmp1_;
	_tmp2_ = self->priv->_microseconds;
	_tmp3_ = self->timer;
	_tmp4_ = self->priv->_microseconds;
	type_breaker_countdown_set_progress (self, ((gdouble) (_tmp2_ - _tmp3_)) / ((gdouble) _tmp4_));
	_tmp5_ = self->timer;
	_tmp6_ = self->priv->_progress;
	g_signal_emit_by_name (self, "microtick", _tmp5_, _tmp6_);
	_tmp7_ = self->timer;
	_tmp8_ = self->ticked;
	if ((_tmp7_ / 1000) < _tmp8_) {
		guint _tmp9_ = 0U;
		gdouble _tmp10_ = 0.0;
		guint _tmp11_ = 0U;
		_tmp9_ = self->ticked;
		_tmp10_ = self->priv->_progress;
		g_signal_emit_by_name (self, "tick", _tmp9_, _tmp10_);
		_tmp11_ = self->ticked;
		self->ticked = _tmp11_ - 1;
	}
	_tmp12_ = self->timer;
	if (_tmp12_ <= ((guint) 0)) {
		g_signal_emit_by_name (self, "zero");
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


gdouble type_breaker_countdown_get_progress (TypeBreakerCountdown* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_progress;
	result = _tmp0_;
	return result;
}


void type_breaker_countdown_set_progress (TypeBreakerCountdown* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_progress = _tmp0_;
}


guint type_breaker_countdown_get_microseconds (TypeBreakerCountdown* self) {
	guint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_microseconds;
	result = _tmp0_;
	return result;
}


void type_breaker_countdown_set_microseconds (TypeBreakerCountdown* self, guint value) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_microseconds = _tmp0_;
}


static void g_cclosure_user_marshal_VOID__UINT_DOUBLE (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__UINT_DOUBLE) (gpointer data1, guint arg_1, gdouble arg_2, gpointer data2);
	register GMarshalFunc_VOID__UINT_DOUBLE callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__UINT_DOUBLE) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_uint (param_values + 1), g_value_get_double (param_values + 2), data2);
}


static void type_breaker_value_countdown_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void type_breaker_value_countdown_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		type_breaker_countdown_unref (value->data[0].v_pointer);
	}
}


static void type_breaker_value_countdown_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = type_breaker_countdown_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer type_breaker_value_countdown_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* type_breaker_value_countdown_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TypeBreakerCountdown* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = type_breaker_countdown_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* type_breaker_value_countdown_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TypeBreakerCountdown** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = type_breaker_countdown_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* type_breaker_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TypeBreakerParamSpecCountdown* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_BREAKER_TYPE_COUNTDOWN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer type_breaker_value_get_countdown (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BREAKER_TYPE_COUNTDOWN), NULL);
	return value->data[0].v_pointer;
}


void type_breaker_value_set_countdown (GValue* value, gpointer v_object) {
	TypeBreakerCountdown* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BREAKER_TYPE_COUNTDOWN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BREAKER_TYPE_COUNTDOWN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		type_breaker_countdown_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		type_breaker_countdown_unref (old);
	}
}


void type_breaker_value_take_countdown (GValue* value, gpointer v_object) {
	TypeBreakerCountdown* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BREAKER_TYPE_COUNTDOWN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BREAKER_TYPE_COUNTDOWN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		type_breaker_countdown_unref (old);
	}
}


static void type_breaker_countdown_class_init (TypeBreakerCountdownClass * klass) {
	type_breaker_countdown_parent_class = g_type_class_peek_parent (klass);
	((TypeBreakerCountdownClass *) klass)->finalize = type_breaker_countdown_finalize;
	g_type_class_add_private (klass, sizeof (TypeBreakerCountdownPrivate));
	g_signal_new ("tick", TYPE_BREAKER_TYPE_COUNTDOWN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__UINT_DOUBLE, G_TYPE_NONE, 2, G_TYPE_UINT, G_TYPE_DOUBLE);
	g_signal_new ("microtick", TYPE_BREAKER_TYPE_COUNTDOWN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__UINT_DOUBLE, G_TYPE_NONE, 2, G_TYPE_UINT, G_TYPE_DOUBLE);
	g_signal_new ("zero", TYPE_BREAKER_TYPE_COUNTDOWN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void type_breaker_countdown_instance_init (TypeBreakerCountdown * self) {
	self->priv = TYPE_BREAKER_COUNTDOWN_GET_PRIVATE (self);
	self->priv->interval = (guint) 50;
	self->ref_count = 1;
}


static void type_breaker_countdown_finalize (TypeBreakerCountdown* obj) {
	TypeBreakerCountdown * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BREAKER_TYPE_COUNTDOWN, TypeBreakerCountdown);
	g_signal_handlers_destroy (self);
}


GType type_breaker_countdown_get_type (void) {
	static volatile gsize type_breaker_countdown_type_id__volatile = 0;
	if (g_once_init_enter (&type_breaker_countdown_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { type_breaker_value_countdown_init, type_breaker_value_countdown_free_value, type_breaker_value_countdown_copy_value, type_breaker_value_countdown_peek_pointer, "p", type_breaker_value_countdown_collect_value, "p", type_breaker_value_countdown_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TypeBreakerCountdownClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) type_breaker_countdown_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TypeBreakerCountdown), 0, (GInstanceInitFunc) type_breaker_countdown_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType type_breaker_countdown_type_id;
		type_breaker_countdown_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TypeBreakerCountdown", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&type_breaker_countdown_type_id__volatile, type_breaker_countdown_type_id);
	}
	return type_breaker_countdown_type_id__volatile;
}


gpointer type_breaker_countdown_ref (gpointer instance) {
	TypeBreakerCountdown* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void type_breaker_countdown_unref (gpointer instance) {
	TypeBreakerCountdown* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TYPE_BREAKER_COUNTDOWN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



